---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Home
- type: directory
  path: testimonies
  label: Testimonies
  create: documents
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - testimony
- type: heading
  label: Services
- type: directory
  path: services
  label: Services List
  create: all
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - services
- type: heading
  label: Targets
- type: document
  path: data/targets_page.json
  label: Targets Page
- type: directory
  path: targets
  label: Targets List
  create: all
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - target
- type: heading
  label: Blog
- type: directory
  path: blog
  label: Blog Posts
  create: documents
  match: "**/*.md"
  templates:
  - blog
- type: heading
  label: About Us
- type: heading
  label: Others
- type: document
  path: data/theme.json
  label: Theme config
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
