---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Home
- type: document
  path: data/home_page.json
  label: Home Page
  match: "**/*"
- type: heading
  label: Services
- type: document
  path: data/services_page.json
  label: Services Page
- type: heading
  label: Targets
- type: document
  path: data/targets_page.json
  label: Targets Page
  match: "**/*"
- type: heading
  label: Blog
- type: document
  path: data/blog_page.json
  label: Blogs Page
  match: "**/*"
- type: heading
  label: About Us
- type: heading
  label: Others
- type: document
  path: data/socials.json
  label: Social Media Links
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
