---
label: Services
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
  description: Title of the service
- name: image
  type: file
  config:
    maxSize: 250
  label: Image
  description: put an image for the service
- name: history
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: History
  description: Some history of the service
- name: introduction
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Introduction
  description: Write a summary that will give the user an idea of what the service
    is
- name: benefits
  type: field_group_list
  fields:
  - name: benefit
    type: text
    config:
      required: false
    label: Benefit
  config:
    min: 
    max: 
    labelField: 
  label: Benefits
- name: test
  type: blocks
  label: Test
  template_types: []
  config:
    min: 
    max: 
pages:
- services/service-1.md
